BEGIN TRANSACTION;

DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS bundles;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS dishes_ingredients;
DROP TABLE IF EXISTS dishes_resources;
DROP TABLE IF EXISTS bundles_dishes;
DROP TABLE IF EXISTS subscription_orders;

COMMIT;